### ISSUE TITLE
Windows & Linux version

### ISSUE THREAD

**Issue by tlkw79** [rpineau/FlatFielderControl#1]
Hi,

Are you planning to make this app also available for Windows and Linux too? 

Thanks

Tom

**Comment by rpineau** [comment]
There is a Python version that works on Linux (and probably Windows) : https://rti-zone-files.s3.amazonaws.com/flatman_ctl.py
The current code is in Obj-C and is not really portable to Linux or Windows.
Also .. I'm not a Windows developer so a direct port of this application Window will not happen.
A Qt version for Linux .. may be one day.. but I really don't have time for it now.

**Comment by rpineau** [comment]
Also... for windows, Optec has a standalone app :  https://optecinc.com/astronomy/downloads/alnitak.htm
